targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/state/*.dart
            - lib/state/**/*.dart
            - lib/actions/*.dart
            - lib/**/exception/*.dart
            - lib/**/entity/*.dart
        options:
          any_map: true
          explicit_to_json: true
