targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/state/*.dart
            - lib/state/**/*.dart
            - lib/actions/*.dart
#       json_serializable:
#         generate_for:
#           include:
#             - lib/model/firestore/**/*.dart
        options:
          any_map: true
          explicit_to_json: true
